.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH L2TPNS 8 "November 16, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
l2tpns \- L2TP LNS daemon
.SH SYNOPSIS
.B l2tpns
[ \fB-d\fR ] [ \fB-c\fR \fI<file>\fR ] [ \fB-h\fR \fI<hostname>\fR ] [ \fB-a\fR \fI<address>\fR ] [ \fB-v\fR ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B l2tpns
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBl2tpns\fP is an L2TP LNS daemon that doesn't require kernel support
for PPP or L2TP, nor any kernel patches. For more information on L2TP see
RFC 2661.
.PP
Once running l2tpns can be controlled by telnetting to port 23 on the
machine running the daemon.
.SH OPTIONS
.TP
.B \-d
Detach from terminal and fork into the background. By default l2tpns
will stay in the foreground.
.TP
.B \-c <file>
Specify config file.
.TP
.B \-h <hostname>
Force hostname to <hostname>.
.TP
.B \-v
Increase verbosity for debugging. Can be used multiple times.
.br
.SH FILES
.TP
\fB\fI/etc/l2tpns/startup-config\fR
The default configuration file.
.TP
\fB\fI/etc/l2tpns/ip_pool\fR
IP address pool configuration.
.TP
\fB\fI/etc/l2tpns/users\fR
Username/password configuration for access to admin interface.
.SH SEE ALSO
\fInsctl\fR(8)
.SH AUTHOR
This manual page was written by Jonathan McDowell <noodles@earth.li>,
for the Debian GNU/Linux system (but may be used by others).

